# Generated by Django 4.2 on 2023-04-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('Ubcacion', models.CharField(max_length=200)),
                ('Direccion', models.CharField(max_length=200)),
                ('contraseña', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('tipo_doc', models.CharField(max_length=200)),
                ('N_doc', models.IntegerField(max_length=200)),
                ('N_cel', models.IntegerField(max_length=200)),
                ('Medio_trans', models.CharField(max_length=200)),
                ('Fecha_exp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
